# Generated by Django 2.1.4 on 2020-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200522_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='implementation',
        ),
        migrations.AddField(
            model_name='project',
            name='implementation_link',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(max_length=300),
        ),
    ]
